name: mobile
description: "The Map Project - Real-time Road Intelligence"
publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  supabase_flutter: ^2.16.0
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  geolocator: ^14.0.3
  flutter_dotenv: ^6.0.0
  http: ^1.6.0
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  url_launcher: ^6.3.2
  flutter_local_notifications: ^22.3.0
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.3.0
  multicast_dns: ^0.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"